FROM nginx:alpine

# Zkopíruje Nginx konfiguraci
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Zkopíruje statické soubory
COPY index.html /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY app.js /usr/share/nginx/html/
COPY bg3d.js /usr/share/nginx/html/

# Nastavení práv
RUN chmod -R 755 /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
